<?php echo $this->importResource('gres', 'css', 'JDialog-custom.css')?>
<?php echo $this->importResource('cres', 'css', 'app/tuonews/site/default/skin/default/css/common.css')?>
<?php echo $this->importResource('cres', 'css', 'app/tuonews/site/default/skin/default/css/news.css')?>
<?php echo $this->importResource('cres', 'css', 'app/tuonews/site/default/skin/default/css/custom_tuonews.css')?>
<?php echo $this->importResource('gres', 'js', 'jquery-1.11.2.min.js')?>
<?php echo $this->importResource('gres', 'js', 'jquery.lazyload.min.js')?>
<?php echo $this->importResource('gres', 'js', 'JDialog.js')?>
<?php echo $this->importResource('gres', 'js', 'JForm.js')?>
<?php echo $this->importResource('gres', 'js', 'AjaxProxy.js')?>
<?php echo $this->importResource('gres', 'js', 'slider.js')?>
<?php echo $this->importResource('cres', 'js', '/app/tuonews/site/default/js/common.js')?>
